django/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

rest_framework/runtests/urls.py
"""
Blank URLConf just to keep runtests.py happy.
"""
from rest_framework.compat import patterns

urlpatterns = patterns('',
)

rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication.

The urls must be namespaced as 'rest_framework', and you should make sure
your authentication settings include `SessionAuthentication`.

    urlpatterns = patterns('',
        ...
        url(r'^auth', include('rest_framework.urls', namespace='rest_framework'))
    )
"""
from __future__ import unicode_literals
from rest_framework.compat import patterns, url


template_name = {'template_name': 'rest_framework/login.html'}

urlpatterns = patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', template_name, name='login'),
    url(r'^logout/$', 'logout', template_name, name='logout'),
)

urls.py
from django.conf.urls import *
from django.contrib import admin
import dbindexer
from django.views.generic import TemplateView
from links.views import LinkListView
from links.views import LinkNewestView
from links.views import UserProfileDetailView
from django.contrib.auth.decorators import login_required as auth
from links.views import UserProfileEditView
from links.views import LinkCreateView
from links.views import LinkDetailView
from links.views import LinkUpdateView
from links.views import LinkDeleteView
from links.views import VoteFormView
from links.views import fetchRss
from links.views import fetchRs2
from links.views import derank
from links.views import rerank
from links.views import api


handler500 = 'djangotoolbox.errorviews.server_error'

# django admin
admin.autodiscover()

# search for dbindexes.py in all INSTALLED_APPS and load them
dbindexer.autodiscover()



urlpatterns = patterns('',
    ('^_ah/warmup$', 'djangoappengine.views.warmup'),
    url(r'^$', LinkListView.as_view(), name='home'),
    url(r'^newest/$', LinkNewestView.as_view(), name='newest'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', name="logout"),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^users/(?P<slug>\w+)/$', UserProfileDetailView.as_view(), name="profile"),
    url(r'^edit_profile/$', auth(UserProfileEditView.as_view()), name="edit_profile"),
    url(r'^link/create/$', auth(LinkCreateView.as_view()),  name='link_create'),
    url(r'^link/(?P<pk>\d+)/$', LinkDetailView.as_view(),   name='link_detail'),
    url(r'^link/update/(?P<pk>\d+)/$', auth(LinkUpdateView.as_view()),  name='link_update'),
    url(r'^link/delete/(?P<pk>\d+)/$', auth(LinkDeleteView.as_view()),  name='link_delete'),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^vote/$', VoteFormView.as_view(), name="vote"),
    url(r'^rerank/$', rerank.as_view()),
    url(r'^derank/$', derank.as_view()),
    url(r'^fetchRss/$', fetchRss.as_view()),
    url(r'^fetchRs2/$', fetchRs2.as_view()),
    url(r'^api/$', api.as_view()),
#    (r'^blog/', include('blog.urls')),
#    (r'^', TemplateView.as_view(template_name="home.html")),
#    #url(r'^$', TemplateView.as_view("home.html")),
#    ('^$', 'django.views.generic.simple.direct_to_template', {'template': 'home.html'}),
    ('^admin/', include(admin.site.urls)),
)

links/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count
from django.core.urlresolvers import reverse
from django.utils.timezone import now


class LinkVoteCountManager(models.Manager):
    def get_query_set(self):
        return super(LinkVoteCountManager, self).get_query_set().annotate(votes=Count('vote')).order_by('-votes')

class Link(models.Model):
    title = models.CharField("Headline", max_length=100, unique=True)
    submitter = models.ForeignKey(User)
    linksource = models.CharField("Linksource", max_length=250)
    submitted_on = models.DateTimeField(auto_now_add=True)
    rank_score = models.FloatField(default=0.0)
    url = models.URLField("URL", max_length=250, blank=True)
    description = models.TextField(blank=True)
#    with_votes = LinkVoteCountManager()
    votes = models.IntegerField(default=1)
    objects = models.Manager() #default manager

    def __unicode__(self):
        return self.title

    def set_rank(self):
        # Based on HN ranking algo at http://amix.dk/blog/post/19574
        SECS_IN_HOUR = float(60*60)
        GRAVITY = 1.2

        delta = now() - self.submitted_on
        item_hour_age = delta.total_seconds() // SECS_IN_HOUR
        votes = self.votes - 1
        self.rank_score = votes / pow((item_hour_age+2), GRAVITY)
        self.save()

'''
    def votes(self):
        num_submissions = Submission.objects.filter(uploaded_by=self).count()
        return num_submissions
'''
    

class Vote(models.Model):
    voter = models.ForeignKey(User)
    link = models.ForeignKey(Link)
#    with_votes = Link.objects.count()
#    with_votes = Link.objects.filter(with_votes__gt=0).annotate(votes=Count('with_votes')).order_by('-votes')


    def __unicode__(self):
        return "%s upvoted %s" % (self.voter.username, self.link.title)

class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True)
    bio = models.TextField(null=True)

    def __unicode__(self):
        return "%s's profile" % self.user

def create_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)

# Signal while saving user
from django.db.models.signals import post_save
post_save.connect(create_profile, sender=User)


def get_absolute_url(self):
    return reverse("link_detail", kwargs={"pk": str(self.id)})

links/forms.py
from django import forms
from .models import UserProfile
from .models import Link
from .models import Vote

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ("user")

class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        exclude = ("submitter", "rank_score", "votes",)

class VoteForm(forms.ModelForm):
    class Meta:
        model = Vote

links/views.py
from rest_framework.renderers import JSONRenderer, XMLRenderer
from rest_framework.parsers import JSONParser
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import mixins
from rest_framework import generics
from rest_framework.parsers import XMLParser
from StringIO import StringIO
from UserString import MutableString
from links.serializers import LinkSerializer, Wikifetch, UserSerializer, ItemSerializer
from django.template import Context, RequestContext
from django.shortcuts import render_to_response, get_object_or_404, render, redirect
from django import http
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.views.decorators.csrf import csrf_exempt
import urllib2, urllib
from django.views.generic import ListView, DetailView
from django.contrib.auth import get_user_model
from .models import UserProfile
from django.contrib.auth.models import User
from .models import Link, Vote
from django.views.generic.edit import UpdateView
from .forms import UserProfileForm
from django.core.urlresolvers import reverse
from django.views.generic.edit import CreateView
from .forms import LinkForm
from django.views.generic import DetailView
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.contrib.comments.models import Comment
from django.views.generic.edit import FormView
from .forms import VoteForm
from .models import Vote
import json
from django.http import HttpResponse
from xml.etree import ElementTree as ET
from django.core.cache import cache
from django.views.decorators.cache import cache_control
import logging
from random import randrange
import re
import AppConfig
from google.appengine.api import urlfetch
from BeautifulSoup import BeautifulSoup
from urlparse import urlparse
from feedparser import parse
from HTMLParser import HTMLParser

TAG_RE = re.compile(r'<[^>]+>')

class rerank(APIView):
    # ...
    @csrf_exempt
    def get(self, request, format=None):
        def rank_all():
            for link in Link.objects.all().order_by('-votes'):
                link.set_rank()

        import time

        def show_all():
#        print "\n".join("%10s %0.2f" % (l.title, l.rank_score,
# #                            ) for l in Link.objects.all())
            print "----\n\n\n"
        rank_all()
        show_all()
        return Response('----------------------')

class derank(APIView):
    # ...
    @csrf_exempt
    def get(self, request, format=None):
        def derank_all():
            for link in Link.objects.all().order_by('rank_score', 'submitted_on')[:20] :
                link.delete()

        import time

        def show_all():
#        print "\n".join("%10s %0.2f" % (l.title, l.rank_score,
# #                            ) for l in Link.objects.all())
            print "----\n\n\n"
        derank_all()
        show_all()
        return Response('----------------------')
    
''' 
    if foo:
        return HttpResponseNotFound('<h1>Page not found</h1>')
    else:
        return HttpResponse('<h1>Page was found</h1>')
'''
class MLStripper(HTMLParser):
    def __init__(self):
        self.reset()
        self.fed = []
    def handle_data(self, d):
        self.fed.append(d)
    def get_data(self):
        return ''.join(self.fed)

class LinkListView(ListView):
    model = Link
#    queryset = Vote.with_votes.all()
    queryset = Link.objects.all().order_by('-rank_score', '-votes')
    paginate_by = 20
    def get_context_data(self, **kwargs):
        context = super(LinkListView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            voted = Vote.objects.filter(voter=self.request.user)
            links_in_page = [link.id for link in context["object_list"]]
            voted = voted.filter(link_id__in=links_in_page)
            voted = voted.values_list('link_id', flat=True)
            context["voted"] = voted
        return context

class LinkNewestView(ListView):
    model = Link
#    queryset = Vote.with_votes.all()
    queryset = Link.objects.all().order_by('-submitted_on')
    paginate_by = 20
    def get_context_data(self, **kwargs):
        context = super(LinkNewestView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            voted = Vote.objects.filter(voter=self.request.user)
            links_in_page = [link.id for link in context["object_list"]]
            voted = voted.filter(link_id__in=links_in_page)
            voted = voted.values_list('link_id', flat=True)
            context["voted"] = voted
        return context

class UserProfileDetailView(DetailView):
    model = get_user_model()
    slug_field = "username"
    template_name = "user_detail.html"

    def get_object(self, queryset=None):
        user = super(UserProfileDetailView, self).get_object(queryset)
        UserProfile.objects.get_or_create(user=user)
        return user

class UserProfileEditView(UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = "edit_profile.html"

    def get_object(self, queryset=None):
        return UserProfile.objects.get_or_create(user=self.request.user)[0]

    def get_success_url(self):
        return reverse("profile", kwargs={'slug': self.request.user})


class LinkCreateView(CreateView):
    model = Link
    form_class = LinkForm

    def form_valid(self, form):
        f = form.save(commit=False)
        f.rank_score = 0.0
        f.submitter = self.request.user
        f.save()

        return super(CreateView, self).form_valid(form)

class LinkUpdateView(UpdateView):
    model = Link
    form_class = LinkForm

class LinkDeleteView(DeleteView):
    model = Link
    success_url = reverse_lazy("home")

class LinkDetailView(DetailView):
    model = Link

	
	
	

class OldVoteFormView(FormView):
    form_class = VoteForm

    def form_valid(self, form):
        link = get_object_or_404(Link, pk=form.data["link"])
        user = self.request.user
        prev_votes = Vote.objects.filter(voter=user, link=link)
        has_voted = (prev_votes.count() > 0)

        if not has_voted:
            # add vote
            Vote.objects.create(voter=user, link=link)
            link.votes +=1
            link.save(update_fields=["votes"]) 
#            Link.objects.filter(link=link).update(views=F('views')+1)
#            n = Link.objects.update(votes=F('votes')+1)  
            print("voted")
            print(link.votes)
        else:
            # delete vote
            prev_votes[0].delete()
            link.votes -=1
            link.save(update_fields=["votes"]) 
            print("unvoted")
            print(link.votes)

        return redirect("home")

    def form_invalid(self, form):
        print("invalid")
        return redirect("home")

class JSONFormMixin(object):
    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict), content_type='application/json')
        response.status = 200 if valid_form else 500
        return response

class VoteFormBaseView(FormView):
    form_class = VoteForm
    

    @csrf_exempt
    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict))
        response.status = 200 if valid_form else 500
        return response

    def form_valid(self, form):
        link = get_object_or_404(Link, pk=form.data["link"])
        if self.request.user.is_authenticated():
            user = self.request.user
            prev_votes = Vote.objects.filter(voter=user, link=link)
            has_voted = (len(prev_votes) > 0)

            ret = {"success": 1}
            if not has_voted:
                # add vote
                v = Vote.objects.create(voter=user, link=link)
                link.votes +=1
                link.save(update_fields=["votes"]) 
                ret["voteobj"] = v.id
            else:
                # delete vote
                link.votes -=1
                link.save(update_fields=["votes"]) 
                prev_votes[0].delete()
                ret["unvoted"] = 1
            return self.create_response(ret, True)
        else:
            ret = {"location": 'login'}
        return self.create_response(ret, True)

    def form_invalid(self, form):
        if self.request.user.is_authenticated():
            ret = {"success": 0, "form_errors": form.errors }
            return self.create_response(ret, False)
        else:
            ret = {"location": 'login'}
        return self.create_response(ret, False)

class VoteFormView(JSONFormMixin, VoteFormBaseView):
    pass



class api(APIView):
    @csrf_exempt
    def get(self, request, format=None):
#    queryset = Vote.with_votes.all()
        MEMCACHE_GREETINGS = 'APILINKS'
        content = cache.get(MEMCACHE_GREETINGS)
        time = 1800 
        if content is None:
            content = Link.objects.all().order_by('-rank_score', '-votes')[:20]
            logging.debug("value of  user my var is %s", str(content))
            serializer = LinkSerializer(content)
            cache.add(MEMCACHE_GREETINGS, serializer.data, time)
            return Response(serializer.data)
        else:
            return Response(content)



class fetchRss(APIView):

#    renderer_classes = (XMLRenderer, JSONRenderer)
#    @cache_control(must_revalidate=True, max_age=3600)
    @csrf_exempt
    def get(self, request, format=None):
        content = MutableString()
        content = []
        opener = urllib2.build_opener()
        opener.addheaders = [('User-agent', 'Mozilla/24.0')]
#        submitter = User.objects.get(username='test')
#        logging.debug("value of  user my var is %s", str(submitter.username))


        def load(durl, greet):
                def remove_tags(text):

templates/links/link_detail.html
{% extends "base.html" %}

{% block meta_title %}{{ object.title }}{% endblock %}
{% block title %}
<a href="{{ object.url }}">{{ object.title }}</a>
<span class="domain">({{ object.domain }})</span>
{% endblock %}
{% load comments %}

{% block main %}
<div class="link-view">
    <p class="description"><!-- object.description !--></p>
    <div class="link-meta">
      
		
							<div class="rating">

						<form method="post" action="{% url 'vote' %}">
						   
						   
						   
						{% csrf_token %}
						<input type="hidden" id="id_link" name="link" class="hidden_id" value="{{ link.pk }}" />
						<input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" />
					<input id="id_object_pk" name="object_pk" type="hidden" value="11903" />




					<div class="form-group input_id_value_0">
						
					 <ul>
					<li><label for="id_value_0"><input id="id_value_0" name="value" type="radio" value="-1" /> -1</label></li>
					<li><label for="id_value_1"><input id="id_value_1" name="value" type="radio" value="1" /> 1</label></li>
					</ul>
						
					</div>
						   
						   
						   
						</form>

						<span class="arrows">
							<a href="#"><i class="icon icon-arrow-up"></i></a>
							<a href="#"><i class="icon icon-arrow-down"></i></a>
						</span>

						<span class="score">
							{{ link.votes }}
						</span>

					</div>
					
					
					
		
		
       by <a class="profile" href="{{ link.url }}">{{ link.submitter }}</a>
        {{  link.submitted_on|timesince  }} ago      
    </div>
	
	</div>
	
	
	
	
	
<div class="comments">
  <h3>Comments</h3>

  <div class="comment_form">
{% if user.is_authenticated %}
  {% get_comment_form for object as form %}
  <form action="{% comment_form_target %}" method="POST">
    {% csrf_token %}
    {{ form.comment }}
   
    {{ form.content_type }}
    {{ form.object_pk }}
    {{ form.timestamp }}
    {{ form.security_hash }}
    <input type="hidden" name="name" value="{{ user }}" />
    <input type="hidden" name="email" value="{{ user.email|default:'d@ummy.com' }}" />
    <input type="hidden" name="url" value="" />
    <input type="hidden" name="next" 
	   value="{% url 'link_detail' pk=object.id %}" />
    <div class="actions">
    <input class="btn btn-warning btn-large" id="id_submit" type="submit" value="Add comment">
   </div>
  </form>
{% else %}
  <p>Please <a href="{% url 'login' %}">log in
  </a> to leave a comment.</p>
{% endif %}
  </div>


  {% render_comment_list for object %}
</div>

	
	
	
	
	
	
	

{% endblock %}

templates/links/link_form.html
{% extends "base.html" %}

{% block meta_title %}New Link{% endblock %}
{% block title %}New Link{% endblock %}


{% block main %}

<form method="post" action="">
  {% csrf_token %}
  <fieldset>{{ form.as_p }}</fieldset>
<div class="actions">
    <input class="btn btn-warning btn-large" type="submit" value="Submit New Link">
</div>
</form>
{% endblock %}

templates/links/link_list.html
{% extends "base.html" %}


{% block meta_title %}{{ title|default:"RapidNewsng" }}{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block main %}
{% load comments %}

{% for link in object_list %}
<div class="link-item clearfix">
    
	{% if not user.is_authenticated %}
	 {% endif %}
    <div class="rating">

    <form method="post" action="{% url 'vote' %}" class="vote_form">
       
	   
	   
	{% csrf_token %}
    <input type="hidden" id="id_link" name="link" class="hidden_id" value="{{ link.pk }}" />
	<input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" />
    <input id="id_object_pk" name="object_pk" type="hidden" value="11903" />

    


<div class="form-group input_id_value_0">


 <ul>
<li><label for="id_value_0"><input id="id_value_0" name="value" type="radio" value="-1" /> -1</label></li>
<li><label for="id_value_1"><input id="id_value_1" name="value" type="radio" value="1" /> 1</label></li>
</ul>
    
</div>
	   
	   
	   
    </form>

    <span class="arrows">
        <a href="#"><i class="icon icon-arrow-up"></i></a>
        <a href="#"><i class="icon icon-arrow-down"></i></a>
    </span>

    <span class="score">
        {{ link.votes }}
    </span>

</div>

	
	
  
   
    <div class="link-detail{% if link.votes < 0 %} link-negative{% endif %}">
        <h2>
            <a href="{{ link.url }}">{{ link.title }}</a>
            <span class="domain">({{ link.linksource }})</span>
        </h2>
        by <a class="profile" href="{{ link.url }}">{{ link.submitter }}</a>
        {{  link.submitted_on|timesince  }} ago |
       
        <a class="comments" href="{% url 'link_detail' pk=link.pk %}">{% get_comment_count for link as comment_count %}{{ comment_count }} comment{{ comment_count|pluralize }}</a>
    </div>
</div>
{% empty %}
<p>{{ no_data }}</p>
{% endfor %}

{% if is_paginated %}
<div class="pagination">
<ul>
    {% if page_obj.has_next %}
	<li class="next">
        <a href="?page={{ page_obj.next_page_number }}">More &raquo;</a>
</li>
    {% endif %}
</ul>
</div>
{% endif %}
{% endblock %}

templates/links/login.html
{% extends "base.html" %}

{% block main %}
<h2>Login</h2>

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
  {% csrf_token %}
  <table>
    <tr>
      <td>{{ form.username.label_tag }}</td>
      <td>{{ form.username }}</td>
    </tr>
    <tr>
      <td>{{ form.password.label_tag }}</td>
      <td>{{ form.password }}</td>
    </tr>
  </table>
  
 <div class="actions">
    <input class="btn btn-warning btn-large" type="submit" value="Login">
</div>
  <input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

templates/links/tag_list.html
{% extends "base.html" %}

{% load mezzanine_tags keyword_tags %}

{% block meta_title %}Tags{% endblock %}
{% block title %}Tags{% endblock %}

{% block main %}
{% keywords_for links.link as tags %}
{% if tags %}
<ul class="tag-cloud">
{% for tag in tags|sort_by:"title" %}
<li>
    <a href="{% url "link_list_tag" tag.slug %}"
        class="tag-weight-{{ tag.weight }}">{{ tag }}</a>
    ({{ tag.item_count }})
</li>
{% endfor %}
</ul>
{% endif %}
{% endblock %}